### ISSUE TITLE
SQL Exception for request and responses

### ISSUE THREAD

**Issue by devFarshadFahimi** [IzyPro/WatchDog#58] opened 2022-08-21 05:51 UTC
I implemented this package for logging in my Web API application to monitor logs 
here is my configurations in my **service collection** : 
` services.AddWatchDogServices(opt =>
        {
            opt.ClearTimeSchedule = WatchDogAutoClearScheduleEnum.Monthly;
            opt.IsAutoClear = true;
            opt.SqlDriverOption = WatchDogSqlDriverEnum.MSSQL;
            opt.SetExternalDbConnString = Configuration.GetConnectionString("DefaultConnection");
        });
`

and here is my **appBuilder** configuration : 
`
        app.UseWatchDogExceptionLogger();
        app.UseWatchDog(opt =>
        {
            opt.WatchPageUsername = "xxxx";
            opt.WatchPagePassword = "xxxx";
        });
`
For any request and response that is success and returns correct value, I have got exception as below
What I'm missing in implementation ? 
Why Logging is not working correctly ?

` at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 646
   at WatchDog.src.Helpers.ExternalDbHelper.InsertWatchLog(WatchLog log)
   at WatchDog.src.Managers.DynamicDBManager.InsertWatchLog(WatchLog log)
   at WatchDog.src.WatchDog.InvokeAsync(HttpContext context)
   at WatchDog.src.WatchDogExceptionLogger.InvokeAsync(HttpContext context)`

**Comment by IzyPro** [comment] 2022-08-23 16:13
Hi @devFarshadFahimi 
Could you send in the full exception
It looks like there is something missing at the start of the exception you sent

**Comment by ksarankumar** [comment] 2022-09-15 17:37
@IzyPro Getting the same exception while using with MS SQL. Exception copied from the clipboard. Can u please look into this?

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean&amp; dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 646
   at WatchDog.src.Helpers.ExternalDbHelper.InsertWatchLog(WatchLog log)
   at WatchDog.src.Managers.DynamicDBManager.InsertWatchLog(WatchLog log)
   at WatchDog.src.WatchDog.InvokeAsync(HttpContext context)
   at WatchDog.src.WatchDogExceptionLogger.InvokeAsync(HttpContext context)




<img width="536" alt="image" src="https://user-images.githubusercontent.com/91750898/190472657-f99379d3-770e-4cfc-976e-41ed0bface27.png">

**Comment by IzyPro** [comment] 2022-09-15 18:00
Hi @ksarankumar 
Please use the bug report template. That will help us gather the necessary information to either advise on next steps or provide a fix.
See the template below:

**Description**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Details (please complete the following information):**
 - Project Type: [e.g. API, MVC]
 - Framework Version [e.g. .NET Core 3.1, .NET 6]
 - WatchDog Version [e.g. 1.3.0, 1.2.1]
 - Database [e.g Default, MySQL]


**Additional context**
Add any other context about the problem here.

**Comment by ksarankumar** [comment] 2022-09-15 18:44
Hi @IzyPro ,
 txs for the reply.  did some debugging, seems like the SQL server is throwing **String or binary data would be truncated. The statement has been terminated** - when it tries to store an API  Path having a length of more than 30 char (for example Path: /api/Catalog/ExampleEndPoint/Saran). tried with the path having less than 30 char long and is working fine.
@devFarshadFahimi  can you please confirm the length of your API path?
 Further, Went and checked the underlying table schema, **_path_** column in **_WatchDog_WatchLog_** table can only store only 30 char.
<img width="399" alt="image" src="https://user-images.githubusercontent.com/91750898/190482624-079b2e73-f68a-4629-82ac-fb52c3914c58.png">
You may check this and try to re-design the schema of all underlying tables used by **WatchDog**.
btw keep up the good work, more power to you 🔥

**Comment by IzyPro** [comment] 2022-09-15 19:00
Great, that has already been fixed and a new version will be deployed soon.

**Comment by IzyPro** [comment] 2022-09-18 12:12
@devFarshadFahimi @ksarankumar 
A new version (v1.3.2) with the fix has been released. Update the WatchDog.NET package in your project and you should be good to go.

**Closed by IzyPro** 2022-09-18 12:12 UTC
